extern constant
	DBISTR_RECLOCKED,
	DBISTR_DETAILRECORDSEXIST,
	DBISTR_NOTSUFFTABLERIGHTS,
	DBISTR_NOTSUFFSQLRIGHTS,
	DBISTR_RECLOCKFAILED,
	DBISTR_KEYVIOL,
	DBISTR_FILELOCKED,
	DBISTR_MINVALERR,
	DBISTR_MAXVALERR,
	DBISTR_REQDERR,
	DBISTR_NULLERROR,
	DBISTR_RANGEERROR,
	DBISTR_TABLEREADONLY,
	DBISTR_NODISKSPACE,
	DBISTR_EOF,
	DBISTR_ALREADYLOCKED,
	DBISTR_UNKNOWNSQL,		// includes FOREIGN KEY violation
	DBISTR_INTEGRITY,
	DBISTR_FOREIGNKEY,
	DBISTR_NONE;

struct TRegularError
{
	int code;
	const char *format;
};

void dbi_message(DBIResult ErrorValue, mstr &m);
