#define DISPID_BEFORENAVIGATE2 250
#define DISPID_NEWWINDOW2 251
#define DISPID_NEWWINDOW3 273
#define DISPID_PROGRESSCHANGE 108
#define DISPID_DOCUMENTCOMPLETE 259
#define DISPID_STATUSTEXTCHANGE 102
#define DISPID_TITLECHANGE 113

#ifndef DISPID_BEFORENAVIGATE
#define DISPID_BEFORENAVIGATE                   100
#define DISPID_NAVIGATECOMPLETE                 101
#define DISPID_STATUSTEXTCHANGE                 102
#define DISPID_QUIT                                             103
#define DISPID_DOWNLOADCOMPLETE                 104
#define DISPID_COMMANDSTATECHANGE               105
#define DISPID_DOWNLOADBEGIN                    106
#define DISPID_NEWWINDOW                                107
#define DISPID_PROGRESSCHANGE                   108
#define DISPID_WINDOWMOVE                               109
#define DISPID_WINDOWRESIZE                             110
#define DISPID_WINDOWACTIVATE                   111
#define DISPID_PROPERTYCHANGE                   112
#define DISPID_TITLECHANGE                              113
#define DISPID_TITLEICONCHANGE                  114
#define DISPID_FRAMEBEFORENAVIGATE              200
#define DISPID_FRAMENAVIGATECOMPLETE    201
#define DISPID_FRAMENEWWINDOW                   204

#define DISPID_NAVIGATECOMPLETE2                252
#define DISPID_ONQUIT                                   253
#define DISPID_ONVISIBLE                                254
#define DISPID_ONTOOLBAR                                255
#define DISPID_ONMENUBAR                                256
#define DISPID_ONSTATUSBAR                              257
#define DISPID_ONFULLSCREEN                             258
#define DISPID_DOCUMENTCOMPLETE                 259
#define DISPID_ONTHEATERMODE                    260
#define DISPID_ONADDRESSBAR                             261
#define DISPID_WINDOWSETRESIZABLE               262
#define DISPID_WINDOWCLOSING                    263
#define DISPID_WINDOWSETLEFT                    264
#define DISPID_WINDOWSETTOP                             265
#define DISPID_WINDOWSETWIDTH                   266
#define DISPID_WINDOWSETHEIGHT                  267
#define DISPID_CLIENTTOHOSTWINDOW               268
#define DISPID_SETSECURELOCKICON                269
#define DISPID_FILEDOWNLOAD                             270
#define DISPID_NAVIGATEERROR                    271
#define DISPID_PRIVACYIMPACTEDSTATECHANGE 272
#endif
