mklink array.cpp common\array.cpp
mklink array.h common\array.h
mklink cacconnect.cpp common\cacconnect.cpp
mklink cacconnect.h common\cacconnect.h
mklink cacdatabase.cpp common\cacdatabase.cpp
mklink cacdatabase.h common\cacdatabase.h
mklink cacquery.cpp common\cacquery.cpp
mklink cacquery.h common\cacquery.h
mklink cactypes.h common\cactypes.h
mklink common.h common\common.h
mklink database.h common\database.h
mklink filename.cpp common\filename.cpp
mklink filename.h common\filename.h
mklink idapiv3.h common\idapiv3.h
mklink memblock.cpp common\memblock.cpp
mklink memblock.h common\memblock.h
mklink message.cpp common\message.cpp
mklink message.h common\message.h
mklink mstr.cpp common\mstr.cpp
mklink mstr.h common\mstr.h
mklink ntl_block.c common\ntl_block.c
mklink ntl_block.h common\ntl_block.h
mklink object.h common\object.h
mklink odbccpv3.lib common\odbccpv3.lib
mklink odbcinstv3.h common\odbcinstv3.h
mklink odbcv3.h common\odbcv3.h
mklink odbcv3.lib common\odbcv3.lib
mklink password.cpp common\password.cpp
mklink password.h common\password.h
mklink pointer.cpp common\pointer.cpp
mklink pointer.h common\pointer.h
mklink vmessage.cpp common\vmessage.cpp
mklink vmessage.h common\vmessage.h
mklink snprintf.c common\snprintf.c
mklink snprintf.h common\snprintf.h
mklink vprinter.h common\vprinter.h
mklink vprinter.c common\vprinter.c
