DROP DATABASE "CAC_REGCOURT";

CREATE DATABASE "CAC_REGCOURT"
WITH OWNER "CAC_REGADMIN"
TEMPLATE "template0"
ENCODING 'WIN1251'
TABLESPACE = pg_default
LC_COLLATE = 'C'
LC_CTYPE = 'Bulgarian_Bulgaria.1251'
CONNECTION LIMIT = -1;

\connect "CAC_REGCOURT" "CAC_REGADMIN"
