/* IB does not allow UNION SELECT ORDER BY or SELECT FROM SELECT... */

CREATE VIEW V_SUBJECT (F_ALIAS, F_SUBJECT, F_NAME, F_OFFICIAL, F_SUMMARY, F_ORDER) AS
SELECT K.F_ALIAS, S.F_SUBJECT, S.F_NAME, 1, R.F_SUBJECT, K.F_ORDER
FROM T_SUBJECT S JOIN T_KIND K ON K.F_KIND = S.F_KIND
LEFT JOIN T_SUBJECT_RANGE R ON R.F_TYPE = S.F_TYPE
AND S.F_SUBJECT BETWEEN R.F_LOW_SUBJECT_RANGE AND R.F_HIGH_SUBJECT_RANGE
AND ((R.F_HIGH_SUBJECT_RANGE - R.F_LOW_SUBJECT_RANGE) <= 99 OR
(SELECT COUNT(E.F_SUBJECT) FROM T_SUBJECT_RANGE E
WHERE E.F_TYPE = S.F_TYPE AND
(E.F_HIGH_SUBJECT_RANGE - E.F_LOW_SUBJECT_RANGE) <= 99) = 0)
WHERE S.F_ATTRIB LIKE '%b%'
UNION
SELECT K.F_ALIAS, S.F_SUBJECT, S.F_NAME, 0, R.F_SUBJECT, K.F_ORDER
FROM T_SUBJECT S JOIN T_KIND K ON K.F_KIND = S.F_KIND
LEFT JOIN T_SUBJECT_RANGE R ON R.F_TYPE = S.F_TYPE
AND S.F_SUBJECT BETWEEN R.F_LOW_SUBJECT_RANGE AND R.F_HIGH_SUBJECT_RANGE
AND ((R.F_HIGH_SUBJECT_RANGE - R.F_LOW_SUBJECT_RANGE) <= 99 OR
(SELECT COUNT(E.F_SUBJECT) FROM T_SUBJECT_RANGE E
WHERE E.F_TYPE = S.F_TYPE AND
(E.F_HIGH_SUBJECT_RANGE - E.F_LOW_SUBJECT_RANGE) <= 99) = 0)
WHERE NOT S.F_ATTRIB LIKE '%b%';

SELECT F_ALIAS, F_SUBJECT, F_NAME, F_OFFICIAL, F_SUMMARY FROM V_SUBJECT
ORDER BY F_ORDER, F_SUBJECT;

DROP VIEW V_SUBJECT;
