INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 11000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 12000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 13000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 14000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 15000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 16000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 17000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 18000, 'Í'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 19000, 'Í'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 22000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 23000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 24000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 25000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 30000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 31000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 32000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 33000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 40000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 41000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 42000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 43000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 44000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 45000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 46000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 47000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 48000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 49000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 49100, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 49200, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 49300, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 50000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 60000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 80000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 90000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 92000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 240000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 70000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 93000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 91000, 'Í'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 100000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 101000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 102000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 103000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 104000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 105000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 106000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 107000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 108000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 109000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 110000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 120000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 130000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 140000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 141000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 142000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 143000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 144000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 145000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 150000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 151000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 152000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 153000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 154000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 155000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 160000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 161000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 162000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 163000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 164000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 170000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 200000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 210000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 220000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 230000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 300000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 310000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 320000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 400000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 410000, 'ß'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 420000, 'ß'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 430000, 'ß'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 440000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 440000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 500000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 500000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 510000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 511000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 520000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 521000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 522000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 523000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 530000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 531000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 532000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 533000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 534000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 510000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 511000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 520000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 521000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 522000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 523000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 530000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 531000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 532000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 533000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 534000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 535000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 536000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 537000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 538000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539100, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539200, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539300, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 540000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 541000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 542000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 535000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 536000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 537000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 538000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539100, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539200, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539300, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 540000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 541000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 542000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 543000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 544000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 545000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546100, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546200, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546300, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546400, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 547000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 548000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 550000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 543000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 544000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 545000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546100, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546200, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546300, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 546400, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 547000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 548000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 550000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 560000, 'E'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 560000, 'z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 60000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 92000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 100000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 240000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 26000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 34000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 81000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 156000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 165000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 166000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 167000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539400, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 539400, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 61000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 450000, 'M'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 450000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 410000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 430050, '½'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 560050, '½'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 90050, 'Í'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 450050, 'E'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 450050, 'z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't';

