INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 200000, 'U'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5000000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 600000, '!'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 700000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 701000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 702000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 703000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 704000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 705000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 706000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 707000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 708000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 709000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 710000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 711000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 712000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 713000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 714000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 715000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 716000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 717000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 718000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 719000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 720000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 730000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 800000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 804000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 805000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 806000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 807000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 808000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 809000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 801000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 802000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 803000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 9000000, 'Ï'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 590000, '['
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 790000, ']'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10100, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10600, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10700, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10800, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 10900, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 11000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 11300, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 11400, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20100, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20200, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20300, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20400, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20600, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20700, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 20900, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21100, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21200, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21300, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21500, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21800, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 30000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 30100, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 30300, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 40000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 60000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 60200, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 60300, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 60400, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 90000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 130000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 150000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 160000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 90300, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 90400, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 100000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 100700, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 110000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 140000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 170000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 210000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 220000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 230000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 240000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 250000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 260000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 270000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 280000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 290000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2100000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2110000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2111000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2112000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2113000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2110000, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2120000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2130000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2140000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2150000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2160000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2170000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2180000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2190000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2210000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2211000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2212000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2213000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2214000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2220000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2221000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2230000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2231000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2240000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2241000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2260000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2261000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2280000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2282000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2283000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2284000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2290000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2280000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 130000, 'ÿ'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 140000, 'ß'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2290000, 'Í'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2280000, '½'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5010900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5011000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5011100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5011200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5011300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5011400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5020900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5021600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5030900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5031000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5031100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5031200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5040900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5041900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5042900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5043900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5044700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5050900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5051000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5060700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5070900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5071900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5072900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5073900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5074000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5074100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5080900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5081900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5082900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5084000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5084100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5084200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5090900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5091900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5092900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5093900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5094000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5094100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5100700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5110000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5120900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5121000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5121100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5121200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5130900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5131900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5132900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133600, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133700, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133800, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5133900, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5134000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5140000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5140100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5140200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5150000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5150100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5150200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5150300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5150400, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5150500, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5160000, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5160100, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5160200, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5160300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 9435000, 'Ï'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 9436000, 'Ï'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 9437000, 'Ï'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 9438000, 'Ï'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 9438100, 'Ï'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 601000, '!'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 602000, '!'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 101400, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2114000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2286000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2287000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2300000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 603000, '!'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 604000, '!'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 605000, '!'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 722000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 723000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 11700, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 11800, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 21900, 'Z'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 101500, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 101500, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 180000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 190000, 'N'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 721000, 'H'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5121300, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2287100, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2410000, 'n'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 2420000, 'T'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5083450, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

INSERT INTO T_ARCHIVE_SUBJECT (F_ARCHIVE_INDEX, F_SUBJECT, F_KIND) SELECT F_ARCHIVE_INDEX, 5099950, 'W'
FROM T_OLD_ARCHIVE_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p';

