UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (10000, 11000, 12000, 13000, 14000, 15000, 16000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 200 AND F_TYPE = 'a')
WHERE F_SUBJECT = 17000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a')
WHERE F_SUBJECT = 18000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 840 AND F_TYPE = 'a')
WHERE F_SUBJECT = 19000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 500 AND F_TYPE = 'a')
WHERE F_SUBJECT = 20000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 520 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (21000, 22000, 23000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (24000, 25000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (30000, 31000, 32000, 33000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 620 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (40000, 41000, 42000, 43000, 44000, 45000, 46000, 47000, 48000, 49000, 49100, 49200, 49300) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1000 AND F_TYPE = 'a')
WHERE F_SUBJECT = 50000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (60000, 80000, 90000, 92000, 240000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT = 70000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT = 93000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a')
WHERE F_SUBJECT = 91000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'a')
WHERE F_SUBJECT = 100000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 420 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (101000, 102000, 103000, 104000, 105000, 106000, 107000, 108000, 109000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 400 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (110000, 120000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1100 AND F_TYPE = 'a')
WHERE F_SUBJECT = 130000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (140000, 141000, 142000, 143000, 144000, 145000, 150000, 151000, 152000, 153000, 154000, 155000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (160000, 161000, 162000, 163000, 164000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 730 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (170000, 200000, 210000, 220000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 700 AND F_TYPE = 'a')
WHERE F_SUBJECT = 230000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 300 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (300000, 310000, 320000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a')
WHERE F_SUBJECT = 400000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3200 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (410000, 420000, 430000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT = 440000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT = 440000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT = 500000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT = 500000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (510000, 511000, 520000, 521000, 522000, 523000, 530000, 531000, 532000, 533000, 534000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT IN (510000, 511000, 520000, 521000, 522000, 523000, 530000, 531000, 532000, 533000, 534000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (535000, 536000, 537000, 538000, 539000, 539100, 539200, 539300, 540000, 541000, 542000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT IN (535000, 536000, 537000, 538000, 539000, 539100, 539200, 539300, 540000, 541000, 542000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (543000, 544000, 545000, 546000, 546100, 546200, 546300, 546400, 547000, 548000, 550000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT IN (543000, 544000, 545000, 546000, 546100, 546200, 546300, 546400, 547000, 548000, 550000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a')
WHERE F_SUBJECT = 560000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 't')
WHERE F_SUBJECT = 560000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 100 AND F_TYPE = 'c')
WHERE F_SUBJECT = 60000 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 120 AND F_TYPE = 'c')
WHERE F_SUBJECT = 92000 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 150 AND F_TYPE = 'c')
WHERE F_SUBJECT = 100000 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 980 AND F_TYPE = 't')
WHERE F_SUBJECT = 240000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (26000, 34000, 81000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 600 AND F_TYPE = 'a')
WHERE F_SUBJECT IN (156000, 165000, 166000, 167000) AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT = 539400 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT = 539400 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 900 AND F_TYPE = 'a')
WHERE F_SUBJECT = 61000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT = 450000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT = 450000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 1200 AND F_TYPE = 'a')
WHERE F_SUBJECT = 410000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3300 AND F_TYPE = 'a')
WHERE F_SUBJECT = 430050 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3150 AND F_TYPE = 'a')
WHERE F_SUBJECT = 560050 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 800 AND F_TYPE = 'a')
WHERE F_SUBJECT = 90050 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 'a')
WHERE F_SUBJECT = 450050 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_II = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_ATTRIB_II = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_RESULTS_II = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_CLOSEDS_II = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_PENALITIES_II = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_REASONS_II = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_II = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_QUICK_REPORT_II = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_VID_II = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't'),
 F_SBES_II = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 3100 AND F_TYPE = 't')
WHERE F_SUBJECT = 450050 AND F_TYPE = 't';

