UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p')
WHERE F_SUBJECT = 200000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT = 5000000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p')
WHERE F_SUBJECT = 600000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (700000, 701000, 702000, 703000, 704000, 705000, 706000, 707000, 708000, 709000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (710000, 711000, 712000, 713000, 714000, 715000, 716000, 717000, 718000, 719000, 720000, 730000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (800000, 804000, 805000, 806000, 807000, 808000, 809000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9002 AND F_TYPE = 'p')
WHERE F_SUBJECT = 801000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9003 AND F_TYPE = 'p')
WHERE F_SUBJECT = 802000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9005 AND F_TYPE = 'p')
WHERE F_SUBJECT = 803000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p')
WHERE F_SUBJECT = 9000000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9600 AND F_TYPE = 'p')
WHERE F_SUBJECT = 590000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9700 AND F_TYPE = 'p')
WHERE F_SUBJECT = 790000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c')
WHERE F_SUBJECT IN (10000, 10100, 10600, 10700, 10800, 10900, 11000, 11300, 11400, 20000, 20100, 20200, 20300, 20400, 20600, 20700, 20900, 21000, 21100, 21200, 21300, 21500, 21800) AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c')
WHERE F_SUBJECT IN (30000, 30100, 30300, 40000, 60000, 60200, 60300, 60400, 90000, 130000, 150000, 160000) AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c')
WHERE F_SUBJECT IN (90300, 90400, 100000, 100700, 110000, 140000, 170000) AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't')
WHERE F_SUBJECT IN (210000, 220000, 230000, 240000, 250000, 260000, 270000, 280000, 290000, 2100000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 't')
WHERE F_SUBJECT IN (2110000, 2111000, 2112000, 2113000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9050 AND F_TYPE = 'c')
WHERE F_SUBJECT = 2110000 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't')
WHERE F_SUBJECT IN (2120000, 2130000, 2140000, 2150000, 2160000, 2170000, 2180000, 2190000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't')
WHERE F_SUBJECT IN (2210000, 2211000, 2212000, 2213000, 2214000, 2220000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9080 AND F_TYPE = 't')
WHERE F_SUBJECT IN (2221000, 2230000, 2231000, 2240000, 2241000, 2260000, 2261000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't')
WHERE F_SUBJECT IN (2280000, 2282000, 2283000, 2284000, 2290000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c')
WHERE F_SUBJECT = 2280000 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'a')
WHERE F_SUBJECT = 130000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'a')
WHERE F_SUBJECT = 140000 AND F_TYPE = 'a';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9500 AND F_TYPE = 'd')
WHERE F_SUBJECT = 2290000 AND F_TYPE = 'd';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9550 AND F_TYPE = 'd')
WHERE F_SUBJECT = 2280000 AND F_TYPE = 'd';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (5010000, 5010100, 5010200, 5010300, 5010400, 5010500, 5010600, 5010700, 5010800, 5010900, 5011000, 5011100, 5011200, 5011300, 5011400, 5020000, 5020100, 5020200, 5020300, 5020400, 5020500, 5020600, 5020700, 5020800, 5020900, 5021000, 5021100, 5021200, 5021300, 5021400, 5021500, 5021600, 5030000, 5030100, 5030200, 5030300, 5030400, 5030500, 5030600, 5030700, 5030800, 5030900, 5031000, 5031100, 5031200) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (5040000, 5040100, 5040200, 5040300, 5040400, 5040500, 5040600, 5040700, 5040800, 5040900, 5041000, 5041100, 5041200, 5041300, 5041400, 5041500, 5041600, 5041700, 5041800, 5041900, 5042000, 5042100, 5042200, 5042300, 5042400, 5042500, 5042600, 5042700, 5042800, 5042900, 5043000, 5043100, 5043200, 5043300, 5043400, 5043500, 5043600, 5043700, 5043800, 5043900, 5044000, 5044100, 5044200, 5044300, 5044400, 5044500, 5044600, 5044700, 5050000, 5050100, 5050200, 5050300, 5050400, 5050500, 5050600, 5050700, 5050800, 5050900, 5051000, 5060000, 5060100, 5060200, 5060300, 5060400, 5060500, 5060600, 5060700) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (5070000, 5070100, 5070200, 5070300, 5070400, 5070500, 5070600, 5070700, 5070800, 5070900, 5071000, 5071100, 5071200, 5071300, 5071400, 5071500, 5071600, 5071700, 5071800, 5071900, 5072000, 5072100, 5072200, 5072300, 5072400, 5072500, 5072600, 5072700, 5072800, 5072900, 5073000, 5073100, 5073200, 5073300, 5073400, 5073500, 5073600, 5073700, 5073800, 5073900, 5074000, 5074100, 5080000, 5080100, 5080200, 5080300, 5080400, 5080500, 5080600, 5080700, 5080800, 5080900, 5081000, 5081100, 5081200, 5081300, 5081400, 5081500, 5081600, 5081700, 5081800, 5081900, 5082000, 5082100, 5082200, 5082300, 5082400, 5082500, 5082600, 5082700, 5082800, 5082900, 5083000, 5083100, 5083200, 5083300, 5083400, 5083500, 5083600, 5083700, 5083800, 5083900, 5084000, 5084100, 5084200, 5090000, 5090100, 5090200, 5090300, 5090400, 5090500, 5090600, 5090700, 5090800, 5090900, 5091000, 5091100, 5091200, 5091300, 5091400, 5091500, 5091600, 5091700, 5091800, 5091900, 5092000, 5092100, 5092200, 5092300, 5092400, 5092500, 5092600, 5092700, 5092800, 5092900, 5093000, 5093100, 5093200, 5093300, 5093400, 5093500, 5093600, 5093700, 5093800, 5093900, 5094000, 5094100) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (5100000, 5100100, 5100200, 5100300, 5100400, 5100500, 5100600, 5100700, 5110000, 5120000, 5120100, 5120200, 5120300, 5120400, 5120500, 5120600, 5120700, 5120800, 5120900, 5121000, 5121100, 5121200, 5130000, 5130100, 5130200, 5130300, 5130400, 5130500, 5130600, 5130700, 5130800, 5130900, 5131000, 5131100, 5131200, 5131300, 5131400, 5131500, 5131600, 5131700, 5131800, 5131900, 5132000, 5132100, 5132200, 5132300, 5132400, 5132500, 5132600, 5132700, 5132800, 5132900, 5133000, 5133100, 5133200, 5133300, 5133400, 5133500, 5133600, 5133700, 5133800, 5133900, 5134000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (5140000, 5140100, 5140200, 5150000, 5150100, 5150200, 5150300, 5150400, 5150500, 5160000, 5160100, 5160200, 5160300) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9200 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (9435000, 9436000, 9437000, 9438000, 9438100) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (601000, 602000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c')
WHERE F_SUBJECT = 101400 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't')
WHERE F_SUBJECT = 2114000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't')
WHERE F_SUBJECT IN (2286000, 2287000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 't')
WHERE F_SUBJECT = 2300000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9400 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (603000, 604000, 605000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p')
WHERE F_SUBJECT IN (722000, 723000) AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c')
WHERE F_SUBJECT IN (11700, 11800, 21900) AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 'c')
WHERE F_SUBJECT = 101500 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't')
WHERE F_SUBJECT IN (101500, 180000) AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'c')
WHERE F_SUBJECT = 190000 AND F_TYPE = 'c';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9004 AND F_TYPE = 'p')
WHERE F_SUBJECT = 721000 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT = 5121300 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't')
WHERE F_SUBJECT = 2287100 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't')
WHERE F_SUBJECT = 2410000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9100 AND F_TYPE = 't')
WHERE F_SUBJECT = 2420000 AND F_TYPE = 't';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT = 5083450 AND F_TYPE = 'p';

UPDATE T_SUBJECT SET
 F_FLAGS_I = (SELECT F_FLAGS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_ATTRIB_I = (SELECT F_ATTRIB FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_RESULTS_I = (SELECT F_RESULTS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_CLOSEDS_I = (SELECT F_CLOSEDS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_PENALITIES_I = (SELECT F_PENALITIES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_REASONS_I = (SELECT F_REASONS FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_JUDGE_REPORT_I = (SELECT F_JUDGE_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_QUICK_REPORT_I = (SELECT F_QUICK_REPORT FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_VID_I = (SELECT F_VID FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p'),
 F_SBES_I = (SELECT F_SBES FROM T_OLD_SUBJECT WHERE F_SUBJECT = 9000 AND F_TYPE = 'p')
WHERE F_SUBJECT = 5099950 AND F_TYPE = 'p';

